---

- hosts: ubuntu2.my
  become: yes
  tasks:
   - name: Install PHP on Debian Family
     apt:
        name=php7.4-fpm
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        php7.4 systemd

  handlers:
  -  name: PHP systemd
     systemd:
       name: php7.4-fpm.service
       enabled: yes
       state: restarted
