---

- hosts: ubuntu2.my
  become: yes
  tasks:
  -  name: Install nginx on RedHat Family
     yum:
        name=nginx
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        nginx systemd
        
  -  name: Install nginx on Debian Family
     apt:
        name=nginx
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        nginx systemd

  handlers:
  -  name: nginx systemd
     systemd:
      name: nginx.service
      enabled: yes
      state: restarted
