---

- hosts: ubuntu2.my
  become: yes
  tasks:
   - name: Install bind on Debian Family
     apt:
        name=bind9
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        named systemd

  handlers:
  -  name: bind systemd
     systemd:
       name: named.service
       enabled: yes
       state: restarted
